name: Workflow helpers
on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      # Don't bother testing if we're only updating the changelog.
      - "**.md"
    branches:
      - "**"

jobs:
  workflow-helpers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.0

      - name: Install Dependencies
        run: poetry install

      - name: Test with pytest
        run: |
          poetry run pytest --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Build
        run: poetry build
