name: GitHub Actions Demo
on:
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        working-directory: workflow-helpers
        run: |
          poetry install
      - name: Test with pytest
        working-directory: workflow-helpers
        run: |
          poetry run pytest --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
